services: 
  # docker run -d --name web1 --net mynetwork jmalloc/echo-server
  web:
    #container_name: web1
    image: jmalloc/echo-server
    #networks: 
    #  - mynetwork

 
  # docker run -d --name haproxy --net mynetwork \
  # -v $(pwd)/config:/usr/local/etc/haproxy:ro \
  # -p 80:80 \
  # haproxytech/haproxy-alpine:2.7
  haproxy:
    #container_name: haproxy
    image: haproxytech/haproxy-alpine:2.7
    #networks:
    #  - mynetwork
    volumes: 
      - "./config:/usr/local/etc/haproxy:ro"
    ports:
      - "80:80"
    depends_on: 
      - web
      
# docker network create mynetwork
#networks:
#  mynetwork:
